-- begin SPEEDYPIZZAAPP_ORDER_DETAILS
alter table SPEEDYPIZZAAPP_ORDER_DETAILS add constraint FK_SPEEDYPIZZAAPP_ORDER_DETAILS_ON_ORDER foreign key (ORDER_ID) references SPEEDYPIZZAAPP_ORDERS(ID)^
alter table SPEEDYPIZZAAPP_ORDER_DETAILS add constraint FK_SPEEDYPIZZAAPP_ORDER_DETAILS_ON_DISH foreign key (DISH_ID) references SPEEDYPIZZAAPP_DISH(ID)^
create index IDX_SPEEDYPIZZAAPP_ORDER_DETAILS_ON_ORDER on SPEEDYPIZZAAPP_ORDER_DETAILS (ORDER_ID)^
create index IDX_SPEEDYPIZZAAPP_ORDER_DETAILS_ON_DISH on SPEEDYPIZZAAPP_ORDER_DETAILS (DISH_ID)^
-- end SPEEDYPIZZAAPP_ORDER_DETAILS
-- begin SPEEDYPIZZAAPP_DISH
alter table SPEEDYPIZZAAPP_DISH add constraint FK_SPEEDYPIZZAAPP_DISH_ON_DISH_TYPE foreign key (DISH_TYPE_ID) references SPEEDYPIZZAAPP_DISH_TYPE(ID)^
create index IDX_SPEEDYPIZZAAPP_DISH_ON_DISH_TYPE on SPEEDYPIZZAAPP_DISH (DISH_TYPE_ID)^
-- end SPEEDYPIZZAAPP_DISH
-- begin SPEEDYPIZZAAPP_DISH_TYPE
create unique index IDX_SPEEDYPIZZAAPP_DISH_TYPE_UNIQ_NAME on SPEEDYPIZZAAPP_DISH_TYPE (NAME) ^
-- end SPEEDYPIZZAAPP_DISH_TYPE
-- begin SPEEDYPIZZAAPP_CUSTOMER
create unique index IDX_SPEEDYPIZZAAPP_CUSTOMER_UNIQ_PHONE_NUMBER on SPEEDYPIZZAAPP_CUSTOMER (PHONE_NUMBER) ^
-- end SPEEDYPIZZAAPP_CUSTOMER
-- begin SPEEDYPIZZAAPP_ORDERS
alter table SPEEDYPIZZAAPP_ORDERS add constraint FK_SPEEDYPIZZAAPP_ORDERS_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references SPEEDYPIZZAAPP_EMPLOYEE(ID)^
alter table SPEEDYPIZZAAPP_ORDERS add constraint FK_SPEEDYPIZZAAPP_ORDERS_ON_CUSTOMER foreign key (CUSTOMER_ID) references SPEEDYPIZZAAPP_CUSTOMER(ID)^
create index IDX_SPEEDYPIZZAAPP_ORDERS_ON_EMPLOYEE on SPEEDYPIZZAAPP_ORDERS (EMPLOYEE_ID)^
create index IDX_SPEEDYPIZZAAPP_ORDERS_ON_CUSTOMER on SPEEDYPIZZAAPP_ORDERS (CUSTOMER_ID)^
-- end SPEEDYPIZZAAPP_ORDERS
-- begin SPEEDYPIZZAAPP_INGREDIENTS_DISH_LINK
alter table SPEEDYPIZZAAPP_INGREDIENTS_DISH_LINK add constraint FK_INGDIS_ON_INGREDIENTS foreign key (INGREDIENTS_ID) references SPEEDYPIZZAAPP_INGREDIENTS(ID)^
alter table SPEEDYPIZZAAPP_INGREDIENTS_DISH_LINK add constraint FK_INGDIS_ON_DISH foreign key (DISH_ID) references SPEEDYPIZZAAPP_DISH(ID)^
-- end SPEEDYPIZZAAPP_INGREDIENTS_DISH_LINK
-- begin SPEEDYPIZZAAPP_EMPLOYEE
alter table SPEEDYPIZZAAPP_EMPLOYEE add constraint FK_SPEEDYPIZZAAPP_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SPEEDYPIZZAAPP_EMPLOYEE_ON_USER on SPEEDYPIZZAAPP_EMPLOYEE (USER_ID)^
-- end SPEEDYPIZZAAPP_EMPLOYEE
