alter table SPEEDYPIZZAAPP_EMPLOYEE add constraint FK_SPEEDYPIZZAAPP_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_SPEEDYPIZZAAPP_EMPLOYEE_ON_USER on SPEEDYPIZZAAPP_EMPLOYEE (USER_ID);
